tests/testBoard.cpp
=> tests for redefined boardmove

src/search.cpp, src/search.hpp, src/uci.cpp, src/uci.hpp
Alpha beta is an improvement.
To do: test changing this to return score instead to fully embodiy soft bound rather than hard bound.
=> Alpha beta

CMakeLists.txt, src/board.cpp, src/eval.cpp, src/inCheck.cpp, src/types.hpp, tests/CMakeLists.txt, tests/testBoard.cpp, tests/testSearch.cpp
=> materialDifference

src/moveGen.cpp, src/search.cpp, src/uci.cpp, tests/testBoard.cpp, tests/testInCheck.cpp
=> avoid copy constructors where possible

src/uci.cpp
Forgot to merge this in the previous PR. No functional change.
=> setoption -> setOption

src/bitboard.cpp, src/bitboard.hpp
Played at 10s + 0.1s. No change in strength.
=> minor changes

src/board.cpp, tests/testBoard.cpp
The en passant file keys were not turned off correctly for all moves besides an en passant. 
Testing is currently being done to check for regression.
=> Zobrist Hashing Edge Case

CMakeLists.txt, src/movePicker.cpp, src/movePicker.hpp, src/search.cpp, src/search.hpp, src/timeman.cpp, src/uci.cpp, src/uci.hpp, tests/CMakeLists.txt
* init movePicker
* add movePicker to CMake
* clarify score moves in comment
* default depth 6
=> Move ordering + increase default depth to 6 (#101)

src/move.cpp
=> remove space from move string representation

src/move.cpp, tests/CMakeLists.txt, tests/testSearch.cpp
There are no tests that are being used here.
No functional change.
=> remove testSearch.cpp

src/bitboard.cpp, src/board.cpp, tests/testBitBoard.cpp, tests/testBoard.cpp
This is for code clarity, and there is now code coverage for the asserts. No functional change.
=> move around asserts

tests/testBitBoard.cpp, tests/testBoard.cpp, tests/testMoveGen.cpp
=> Clean up tests

src/search.cpp, src/search.hpp, src/uci.cpp, src/uci.hpp
This is mostly a quality of life change for running matches on Cutechess, as we now get to know what Blocky is thinking while playing. No playing strength change.
=> Output info in search, not uci

CMakeLists.txt, src/attacks.hpp, src/board.cpp, src/board.hpp, src/eval.cpp, src/eval.hpp, src/main.cpp, src/moveGen.cpp, src/moveOrder.cpp, src/moveOrder.hpp, src/search.cpp, src/search.hpp, src/timeman.cpp, src/timeman.hpp, src/ttable.hpp, src/types.hpp, src/uci.cpp, src/uci.hpp, tests/CMakeLists.txt, tests/testBoard.cpp
There should be no functional change. This is mostly done to make development easier in the future.
```
Games: N=1305 W=551 L=523 D=231
Elo: 7.5 +/- 17.1
Alpha: 0.05
Beta: 0.05
Elo0: -15
Elo1: 0
```
=> Cleanup code

tests/testBoard.cpp
=> HOTFIX: Update tests as well for cleanup

src/board.cpp, src/board.hpp, src/eval.cpp, src/eval.hpp, src/search.cpp, tests/testBoard.cpp
=> Refactor Eval

src/board.cpp, src/board.hpp
Eval is already incrementally updated with undoMove(). Also no change in benmch.
=> Addendum: Don't store eval in moveHistory

src/moveGen.cpp, src/moveGen.hpp
=> Clean up some move gen code

CMakeLists.txt
```
Games: N=1366 W=598 L=496 D=272
Elo: 26.0 +/- 16.5
Bench: 6922089 (No change)
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
```
=> Add compiler flag -ftlo

src/search.cpp
```
Games: N=6332 W=2635 L=2461 D=1236
Elo: 9.5 +/- 7.7
Bench: 6384059
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
```
=> Increase pruning with NMP

src/bench.hpp
=> Increase bench depth to 8

src/board.cpp, src/moveGen.cpp, src/moveGen.hpp, src/perft.hpp
Using references for perft is for minor speed gains.
=> Some code cleanups

src/search.cpp
This was originally supposed to be a nonfunctional style change, but a bug was uncovered that prevented bestscore from being updated on beta cutoffs. This fixes that.
```
Games: N=168 W=81 L=22 D=65
Elo: 127.4 +/- 42.2
Bench: 7614418
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
```
=> Update bestscore on beta cutoffs as well

src/search.cpp
```
Games: N=590 W=210 L=141 D=239
Elo: 40.8 +/- 21.7
Bench: 3370151
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
```
=> Tighten RFP

src/search.cpp
Reverts knguy22/Blocky-Chess-Engine#188
The test was not performed against an updated version of main.
=> Revert "Tighten RFP"

src/moveOrder.cpp, src/moveOrder.hpp, src/perft.hpp, src/search.cpp, src/search.hpp, src/uci.cpp
```
Games: N=1111 W=346 L=273 D=492
Elo: 22.9 +/- 15.2
Bench: 3495283
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
```
=> Don't reuse history tables between searches

src/search.cpp
```
LLR: 2.96 (-2.94, 2.94) [0.0, 10.0]
Games: N=4496 W=1292 L=1171 D=2033
Elo: 9.4 +/- 7.5
Bench: 3096002
```
=> Make NMP scale linearly instead of constant

src/search.cpp
```
LLR: 2.97 (-2.94, 2.94) [0.0, 10.0]
Games: N=7841 W=2062 L=1897 D=3882
Elo: 7.3 +/- 5.5
Bench: 2221603
```
=> Make LMR more aggressive

tools/tune/texelBlocky.cpp, tools/tune/texelBlocky.hpp
This should theoretically make it easier to add more HCE features to the texel tuner. This project structure was inspired by Weiss.
=> Refactor Texel

src/board.cpp, src/board.hpp, src/search.cpp, tests/testEval.cpp, tools/tune/texelBlocky.cpp
```
LLR: 2.98 (-2.94, 2.94) [0.0, 8.0]
Games: N=7294 W=1995 L=1843 D=3456
Elo: 7.2 +/- 5.8
Bench: 2030562
```
=> Only NMP with non-Pawn material

src/board.cpp, src/board.hpp, src/move.cpp, src/move.hpp, src/perft.hpp
String outputs were incorrect.
=> Fix string stream outputs

src/search.cpp
Moves that are too late will be pruned and not just reduced.
```
LLR: 2.95 (-2.94, 2.94) [0.0, 8.0]
Games: N=10074 W=2770 L=2586 D=4718
Elo: 6.3 +/- 4.9
Bench: 1622705
```
=> Late Move Pruning

src/search.cpp
```
LLR: 2.99 (-2.94, 2.94) [0.0, 8.0]
Games: N=4984 W=1362 L=1237 D=2385
Elo: 8.7 +/- 7.0
Bench: 1647881
```
=> Make aspiration windows tighter
