knguy22/Blocky-Chess-Engine

- src/board.cpp
- src/board.hpp
- src/moveGen.hpp
- src/types.hpp
- tests/testInCheck.cpp
- tests/testMoveGen.cpp
- tests/testSearch.cpp
Doing this mostly for speed reasons. Even though a the lined changed number looks big, it's mostly just updating the arrays in test cases. Actual code changes are limited to board.cpp and board.hpp.
As for performance, I tried searching to depth 7 from start position timing only the search function, and I think the results speak for themselves.
I will still play some test games to make sure that there's no actual drop in strength or anything.
> use std::array instead of std::vector for board representation

- CMakeLists.txt
- src/timeman.cpp
- src/timeman.hpp
- src/uci.cpp
- src/uci.hpp
Depth 5 on its own loses games to timeout on 1 minute + 0.6 second increment, so I decided to implement a form of time management. The time management is definitely not ideal, though I don't expect to put too much focus on tuning it for the near future unless the time management algorithm becomes more advanced. I expect that to happen after iterative deepening is implemented.
The most important thing is that speedups to search without any loss of evaluation strength can now be tested for improvement in regular matches, as speedups take less time to find a best move for the same depth, meaning that more moves can be evaluated at the maximum depth before time management forces Blocky to use lower depths to conserve time left.
> Increase depth + time management

- CMakeLists.txt
There's pretty much only speedups that can be seen here. I will do some testing just in case to see if the optimizations screwed anything up, but it's unlikely.
> use compiler optimizations gcc

- src/board.cpp
- src/types.hpp
No change in strength.
Interestingly, there appears be a micro-optimization in the makeMove() method. Looking at startpos to depth 5:
**Main**
vs 
**This Branch**
> Redefine piece types

- CMakeLists.txt
- src/board.cpp
- src/board.hpp
- src/search.cpp
- src/types.hpp
- src/uci.cpp
- src/zobrist.cpp
- src/zobrist.hpp
- tests/CMakeLists.txt
- tests/testBoard.cpp
Forgive me for the messy commit history. I was trying out rebasing and did some mistakes. All real commits start at "zobrist hashing definitions"
The main things to take away from this is that all board states are now hashable and have their hashes updated incrementally. This can be used to do a variety of different things including below.
3 Fold Repetition is checked for by having move history contained in a vector during search. Then, it is sorted, and checked to see if three board hashes are in a row. If so, then 3 boards have been repeated on the board, resulting in a draw.
> Zobrist Hashing + 3 Fold Repetition

- src/board.cpp
- src/board.hpp
- src/move.cpp
- src/move.hpp
- src/moveGen.cpp
- tests/testBoard.cpp
I saw that there was some redundant bounds checking in moveGenerator and board, so I decided to clean those up a bit. Even though there were indeed some very minor speed increases, the main point was to remove redundant code. 
Board is no longer responsible for checking for moves to be in bounds, as it should be. After all, it already doesn't check other stuff like if pieces are in between the rook and king for castling. MoveGenerator now uses the inValid() method instead of getPiece() for bounds checking.
> Give Bounds Checking Responsibility to Move Generation

- src/search.cpp
- src/search.hpp
- src/uci.cpp
- src/uci.hpp
In consideration of future efforts to improve search, it should be redefined as a class. Having a shared state for search will generally help make code cleaner while not impacting speed (in fact, speed increases by the tiniest of margins). More parameters will also be able to be defined in search for the future without making the code messier, like it did in the old procedural version.
From startpos with depth 5, main's search currently takes 190,848,362 instructions, while this branch takes 190,839,991.
> Redefine search

- src/bitboard.cpp
- src/bitboard.hpp
- src/board.cpp
- src/move.cpp
- src/move.hpp
- src/moveGen.cpp
- src/moveGen.hpp
- src/timeman.cpp
- src/uci.cpp
- src/uci.hpp
- tests/testBitBoard.cpp
Thinking about migrating move generation to bitboard generation, starting with the knights here. The main issue is checking for correctness of generation. Alpha beta search trees are not the same since the new proposed bitboard method produces moves in a different order, which causes pruning to function differently. 
Here are some depth 4 games. Interestingly, the new version is better at white and worse at black, which makes sense since the bitboard generation generates knight moves towards rank 8 first, which is good for white but bad for black. 
In order to make sure for correctness, perft tests will be expanded and tested for.
> Fast Move Generation For Knights

- CMakeLists.txt
- src/movePicker.cpp
- src/movePicker.hpp
- src/search.cpp
- src/search.hpp
- src/timeman.cpp
- src/uci.cpp
- src/uci.hpp
- tests/CMakeLists.txt
Move ordering is a technique that involves pruning more by searching expected best moves first. This is a naive implementation that will likely make it much more feasible to reach higher depths as Blocky continues to improve. 
Nodes per second will obviously go down due to move ranking, but the expected pruning gains will by far make up for it. Of course, elo testing will have to be done besides these benchmarks.
For example, a search from startpos with depth 7:
Instructions read with depth 6:
> Move ordering + increase default depth to 6

- src/board.cpp
- src/main.cpp
- src/zobrist.cpp
- src/zobrist.hpp
- tests/testBitBoard.cpp
- tests/testBoard.cpp
Right now, the zobrist tables are being created for each construction of a Board, which is inefficient and hurts readability. Instead, Zobrist will be init in main.
> init zobrist keys in a better way; adjust tests to it

- src/bitboard.hpp
- src/eval.hpp
- src/types.hpp
No functional change. Tested with perft depth 5:
> remove unneeded static keyword, replace with constexpr where possible

- src/moveGen.cpp
- src/moveGen.hpp
- tests/testMoveGen.cpp
As described in https://github.com/knguy22/Blocky-Chess-Engine/issues/111, the following fens outputted the wrong number of possible moves. This bug was caused by a faulty function for checking emptiness between king and rook when castling. 
Stockfish's perft was very helpful for tracking this bug, so the perft function has been updated to make this easier to use in the future.
> fixed castling bug + added more information to perft

- src/board.cpp
- src/board.hpp
- src/move.cpp
- src/move.hpp
- src/moveGen.cpp
- src/search.cpp
- tests/testBoard.cpp
- tests/testMoveGen.cpp
The current move generation implementation makes the move and checks for illegality to ensure only legal moves are generated. This is inefficient because legal moves can be performed multiple times: once in movegen and once in search. This is even more egregious because makeMove handles other incrementally updated parts and not all legal moves are made during search, leaving the bulk of runtime being in moveGen.
isLegalMove will only incrementally update the bitboards, which are the essential parts of understanding if a king is left in attack. This results in a large speedup.
```
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
```
> Add isLegalMove function to movegen

- src/board.cpp
- src/search.cpp
- src/search.hpp
- tests/testBoard.cpp
LegalMove doesn't correctly handle en passant captures while the king is in check,. as shown in the fen given in the test case: 
`2RQ4/R6p/6b1/1k5p/Ppp5/8/6P1/7K b - a3 0 42`. This is an amendment to the function to now handle this correctly, though this comes at the cost of speed in the majority of positions. A regression test was ran, but it stopped prematurely due to main (not the hotfix) crashing:
```
WDL: +334 -337 =251
Alpha: 0.05
Beta: 0.05
Elo0: -15
Elo1: 0
Lower bound: -2.94444
Current LLR: 1.00449
Upper bound: 2.94444
```
There is also another bugfix which fixes the way mates are shown in info as well as nodes and depth in certain cases.
> En passant hotfix + UCI bug fixes

- src/board.cpp
- tests/testBoard.cpp
For the given fen, `6k1/8/7p/3K1Ppq/4n3/8/6p1/8 w - g6 0 1`, en passant is incorrectly determined to be a legal move, which is now fixed. This is not expected to be a speed change, so no testing will be done.
> Handle pinned en passant pawns

- src/attacks.cpp
- src/attacks.hpp
- src/bitboard.cpp
- src/bitboard.hpp
- src/board.cpp
- src/board.hpp
- src/moveGen.cpp
- src/moveGen.hpp
- src/search.cpp
- src/uci.cpp
- tests/testBitBoard.cpp
- tests/testMoveGen.cpp
There are already magic bitboards for rooks and bishops, but this patch extends having attack tables for all pieces, which helps with move generation speed. 
```
WDL: +480 =302 -387
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
Lower bound: -2.94
Current LLR: 2.96
Upper bound: 2.94
```
> Attack Tables

- CMakeLists.txt
- src/move.cpp
- src/move.hpp
- src/movePicker.cpp
- src/movePicker.hpp
- src/search.cpp
- src/search.hpp
- src/ttable.cpp
- src/ttable.hpp
- src/uci.cpp
- tests/CMakeLists.txt
Transposition tables help with move ordering between iterative deepening, and incomplete searches can now be used for final moves given that only better moves in incomplete searches overwrite the best move in the previous search.
```
Games: +331 =106 -235
Elo: 50.0 +/- 24.3
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
```
> Transposition Table

- src/search.cpp
- src/search.hpp
Mates would report positive scores irrespective of the losing side. Seldepth basically includes quiescence for now. I stopped the SPRT early for now, but it would've been merged even if regression.
```
Games: N=2423 W=1023 L=1038 D=362
Elo: -2.2 +/- 12.7
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
No result
```
> Fix mate score reporting for losing side + report seldepth

- src/search.cpp
- src/search.hpp
- src/types.hpp
This is mostly done to make development easier in the future.
```
Games: N=866 W=381 L=342 D=143
Elo: 15.7 +/- 21.2
Bench: 26347605
Alpha: 0.05
Beta: 0.05
Elo0: -15
Elo1: 0
```
> Rewrite Search to return int

- src/board.cpp
- src/board.hpp
- src/search.cpp
- src/search.hpp
- src/ttable.cpp
- src/ttable.hpp
There's also some changes to age and depth that doesn't affect the bench like the key size changes did. Those are done to make the code make more sense.
```
Games: N=482 W=244 L=153 D=85
Elo: 66.4 +/- 28.6
Bench: 26355345
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
```
> Use 64 bit keys for TTable

- src/uci.cpp
Command tokens were not cleared in between commands. This fix does so. No functional change.
> BUGFIX: Uci repeated commands

- src/search.cpp
Time up cutting off searches would incorrectly report a score value of 0.
> Don't update score for incomplete search

- src/bench.cpp
- src/search.cpp
- src/search.hpp
- src/timeman.cpp
- src/timeman.hpp
- src/uci.cpp
There are two main changes:
* Searches after an iterative deepening iteration can break when a soft time limit is up. This saves time not doing incompleted searches.
* Increment is accounted for.
```
Games: N=1695 W=722 L=616 D=357
Elo: 21.8 +/- 14.7
Bench: 28577791 (No change)
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
```
> softTimeUp + account for increment

- src/search.cpp
Some positions don't have evals returned correctly because fail hard for beta discards the true value of positions. For example, this fen `8/8/8/3k4/4p3/3bK3/1r6/5r2 b - - 1 61` doesn't correctly return a mate score but a eval of 0, even if the best move is given. This fixes that.
Bench: 28577791 (no change)
> Fail soft to return more accurate evals

- src/moveOrder.cpp
- src/moveOrder.hpp
- src/search.cpp
- src/types.hpp
- src/uci.cpp
Principle Variation Search searches for null windows first for non-PV moves so that bad moves can be rejected quicker. It is surprising that there wasn't more of an elo gain considering how much the bench lowered.
```
Games: N=3382 W=1395 L=1265 D=722
Elo: 13.4 +/- 10.4
Bench: 17744734
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
```
> Principle Variation Search

- src/moveOrder.cpp
- src/moveOrder.hpp
- src/search.cpp
- src/search.hpp
- src/ttable.cpp
- src/ttable.hpp
Evaluations can now be directly returned from the transposition table instead of it just being used for move ordering, which speeds up the time needed for a search. There are also some cleanups, like using key directly to store entries instead of needing an index first.
```
Games: N=504 W=244 L=156 D=104
Elo: 61.3 +/- 27.4
Bench: 13841985
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
```
> Return evaluations from transposition tables

- src/search.cpp
Instead of sorting and using a linear scan after, it's better to just use a linear scan to find 3fold repetition instances. I didn't complete the SPRT for reasons, but it's not really needed to merge something like this:
```
Games: N=2435 W=1024 L=936 D=475
Elo: 12.6+/- 12.4
Bench: 13841985 (Unchanged)
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
Incomplete: LLR 1.89
```
> 3fold detection speedup

- src/bitboard.cpp
- src/bitboard.hpp
- src/board.cpp
- src/board.hpp
- src/eval.cpp
- src/eval.hpp
- src/move.cpp
- src/move.hpp
- src/moveGen.cpp
- src/moveOrder.cpp
- src/search.cpp
- src/ttable.hpp
- src/types.hpp
- tests/testBitBoard.cpp
- tests/testBoard.cpp
- tests/testMoveGen.cpp
This rewrite moves away from using ranks and files and instead squares to keep track of moves for better performance. It also reflects how the engine works at a deeper level.
```
Games: N=1840 W=801 L=691 D=348
Elo: 20.8 +/- 14.3
Bench: 13840838
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
```
> Rewrite BoardMove

- src/board.cpp
- src/board.hpp
- src/search.cpp
- src/types.hpp
Nodes are pruned if a shallower search with a null move still fails high.
```
Games: N=1088 W=483 L=385 D=220
Elo: 31.4 +/- 18.5
Bench: 6922089
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
```
> Null Move Pruning

- src/perft.hpp
There is no need to make move from depth 1 if you're not printing the moves. This results in a 3-4 speedup in perft.
> Batch perft

- src/board.cpp
- src/board.hpp
- src/move.hpp
- src/moveGen.cpp
- src/moveGen.hpp
- src/moveOrder.cpp
- src/moveOrder.hpp
- src/perft.hpp
- src/search.cpp
- src/types.hpp
- tests/CMakeLists.txt
- tests/testMoveGen.cpp
Most moves that are generated are not used due to pruning, so it's more efficient to dynamically generate stages of moves depending on the need. As a result of designing an entirely new move generation, there are some changes to move ordering with captures, which also affects quiescent search:
* Captures scoring correctly handles en-passant
* Promotions to queens are counted as captures
H1 of 5 elo was used to get more games to test that this moveGen doesn't crash.
```
Games: N=311 W=192 L=47 D=72
Elo:  175.5 +/- 36.8
Bench: 4944366
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 5
```
> Staged Move Generation

- src/board.cpp
- src/board.hpp
- src/eval.cpp
- src/eval.hpp
- src/types.hpp
This adds a score to make winning kings approach the enemy king when there is a basic endgame checkmate position on the board like King + Rook vs King. This makes up for deficiencies of the Piece-Square Tables.
```
Games: N=18630 W=6675 L=6392 D=5563
Elo:  5.3 +/- 4.2
Bench: 4944366
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 5
```
> Mop up evaluation

- src/moveOrder.cpp
- src/moveOrder.hpp
- src/search.cpp
Moves that are searched later are more likely to not need full searches, meaning that their depths can be reduced. This is an implementation of the most basic form of LMR possible,  and in the future, enhancements such as using the log formula can be considered.
```
Games: N=1392 W=527 L=436 D=429
Elo: 22.7 +/- 15.2
Bench: 1172276
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
```
> Late Move Reductions (LMR)

- src/search.cpp
```
Games: N=6276 W=2077 L=1921 D=2276
Elo: 8.6 +/- 6.9
Bench: 9710285
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
```
> Don't do LMR on moves that cause checks

- src/moveOrder.cpp
- src/moveOrder.hpp
- src/search.cpp
- src/search.hpp
- src/types.hpp
Killer moves are quiet moves that cause beta cutoffs in sibling nodes. Killer moves are sorted above normal quiet moves.
```
Games: N=645 W=246 L=171 D=228
Elo: 40.6 +/- 21.6
Bench: 7658778
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
```
> Killer Moves

- src/moveOrder.cpp
- src/search.cpp
- src/search.hpp
For MVV-LVA, an extra bonus was given to victim scores so that the most valuable victims are searched fully before moving onto the next ones. This lowered bench somewhat, but previous attempts at using the formula showed negligible change. This is where the unlimited quiescence came in, as deeper quiescence had failed previously without the tweaked MVV-LVA formula.
```
Games: N=1387 W=483 L=398 D=504
Elo: 21.3 +/- 14.6
Bench: 8243970
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
```
> Tweak MVV-LVA + don't depth-limit quiescence

- src/search.cpp
- src/search.hpp
- src/timeman.hpp
This checks system time every 1024 nodes instead, which helps with performance.
```
Games: N=1044 W=385 L=302 D=357
Elo: 27.7 +/- 17.1
Bench: 8243970
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
```
> Don't check system time every node

- src/search.cpp
```
Games: N=1244 W=435 L=352 D=457
Elo: 23.2 +/- 15.4
Bench: 9895955
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
```
> Extend search on moves that gives check

- src/moveOrder.cpp
- src/moveOrder.hpp
- src/search.cpp
- src/ttable.cpp
- src/ttable.hpp
- src/types.hpp
- src/uci.cpp
Typically known as a generalization of killer moves, all beta cutoffs are used to order quiets that are not killers.
```
Games: N=1989 W=622 L=534 D=833
Elo: 15.4 +/- 11.6
Bench: 7446026
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
```
> Butterfly History Tables

- src/search.cpp
- src/search.hpp
This prevents false mates from being reported to UCI.
```
Games: N=6679 W=1905 L=1942 D=2832
Elo: -1.9 +/- 6.3
Bench: 7446026
Alpha: 0.05
Beta: 0.05
Elo0: -10
Elo1: 0
```
> Don't report mate scores from NMP

- src/main.cpp
- src/search.cpp
- src/search.hpp
- src/types.hpp
Instead of doing a fixed depth for late move reductions, reduce based on how late the moves are, as worse quiets tend to be ordered further in the back. 
```
Games: N=3180 W=924 L=832 D=1434
Elo: 11.1 +/- 8.9
Bench: 3633988
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
```
> Log LMR Formula

- src/bitboard.cpp
```
Games: N=3589 W=1031 L=1024 D=1534
Elo:  0.7 +/- 8.6
Bench: 3877065
Alpha: 0.05
Beta: 0.05
Elo0: -10
Elo1: 0
```
> Don't use gcc intrinsics, use standard library for bitboard operations

- src/moveGen.hpp
- src/types.hpp
```
Games: N=447 W=167 L=100 D=180
Elo: 52.5 +/- 25.0
Bench: 3495283
Alpha: 0.05
Beta: 0.05
Elo0: 0
Elo1: 10
```
> Used fixed size arrays instead of vectors for movegen

- src/attacks.cpp
- src/attacks.hpp
This prevents anyone from editing the attack tables outside of init(), which is intended behavior.
```
Games: N=2390 W=669 L=647 D=1074
Elo: 3.2 +/- 10.3
Bench: 3495283
Alpha: 0.05
Beta: 0.05
Elo0: -10
Elo1: 0
```
> Change attacks to a static class

- src/search.cpp
- src/search.hpp
- src/ttable.cpp
- src/ttable.hpp
The replacement strategy was moved to ttable.cpp. The replacement strategy was also changed in that it no longer has wonky behavior, as the old strategy assumed the entry was not replaced between entry access and entry storage. This has been patched with the refactor, so using the old strategy changes bench. Doing always replace keeps the previous bench.
```
LLR: 2.96 (-2.94, 2.94) [-15.0, 0.0]
Games: N=1672 W=465 L=463 D=744
Elo: 0.4 +/- 24.4
Bench: 3495283
```
> Refactor Transposition Table

- src/search.cpp
- src/utils/types.hpp
Quiet moves that are ordered first due to history but do not end up causing beta cutoffs should be penalized so that better moves can be ordered first more quickly.
```
LLR: 2.97 (-2.94, 2.94) [0.0, 10.0]
Games: N=2836 W=794 L=699 D=1343
Elo: 11.6 +/- 9.3
Bench: 2229699
```
> History Malus

- src/search.cpp
```
LLR: 2.98 (-2.94, 2.94) [0.0, 10.0]
Games: N=776 W=236 L=171 D=369
Elo: 29.2 +/- 17.7
Bench: 2249728
```
> Only do NMP for high enough static eval

- src/board.cpp
- src/board.hpp
- src/moveGen.cpp
- src/moveOrder.cpp
- src/search.cpp
- src/uci.cpp
- tests/testBoard.cpp
- tools/tune/extract.cpp
- tools/tune/texelBlocky.cpp
Main changes:
* Board was turned into a class
* All member variables usage outside of Board was replaced with getters or special functions except pieceSets
* Return type style was changed to trailing return types. If this experiment goes well, then trailing return types will be added to the rest of the codebase
The regression test was stopped early due to no visible regressions.
```
LLR: 1.23 (-2.94, 2.94) [-7.0, 0.0]
Games: N=1829 W=478 L=465 D=886
Elo: 2.5 +/- 11.4
Bench: 2249728
```
> Refactor board

- src/search.cpp
- src/ttable.cpp
- src/ttable.hpp
Transposition table entries will generally not be located in cache due to how large transposition tables can be, so prefetching the entries will give speedups, as lookup times will be reduced.
```
LLR: 2.95 (-2.94, 2.94) [0.0, 8.0]
Games: N=3273 W=913 L=808 D=1552
Elo: 11.1 +/- 8.6
Bench:  2249728
```
> Prefetch TTable entries

- src/board.cpp
- src/eval.cpp
- src/eval.hpp
- tools/tune/texelBlocky.cpp
A bonus is given for being the side to move. Attempts were made to tune a phased evaluation version, but they failed to fit to a meaningful value, likely due to the amount of noise in the dataset.
```
LLR: 2.95 (-2.94, 2.94) [0.0, 8.0]
Games: N=1372 W=414 L=329 D=629
Elo: 21.6 +/- 13.5
Bench: 2182440
```
> Tempo evaluation

- src/eval.cpp
- src/eval.hpp
```
LLR: 2.99 (-2.94, 2.94) [-8.0, 0.0]
Games: N=3585 W=943 L=917 D=1725
Elo: 2.5 +/- 8.2
Bench: 2030517
```
> Simplify mop up score

- src/search.cpp
Positions that don't have a TTMove saved typically are searched less and are less important to search deeply.
```
LLR: 2.97 (-2.94, 2.94) [0.0, 8.0]
Games: N=1570 W=438 L=355 D=777
Elo: 18.4 +/- 12.2
Bench: 1614331
```
> Internal Iterative Reductions

- src/board.cpp
- src/board.hpp
- src/search.cpp
- src/ttable.cpp
- src/ttable.hpp
This was never was the colloquial version of age in chess programming. Since always replace is used, "age" can be removed.
```
LLR: 2.98 (-2.94, 2.94) [-8.0, 0.0]
Games: N=2013 W=586 L=537 D=890
Elo: 8.5 +/- 11.3
Bench: 1693445
```
> Simplify "age"
